const PDFDocument = require("pdfkit");
const mongoose = require("mongoose");
const AnalysisReport = require("../models/AnalysisReport");

// ---------- Helpers ----------

const divider = (doc) => {
  doc
    .moveTo(50, doc.y)
    .lineTo(550, doc.y)
    .stroke("#E5E7EB");
  doc.moveDown();
};

const sectionTitle = (doc, text) => {
  doc
    .font("Helvetica-Bold")
    .fontSize(16)
    .fillColor("#4F46E5")
    .text(text);
  doc.moveDown(0.5);
};

const list = (doc, items) => {
  doc.font("Helvetica").fontSize(11).fillColor("#111827");

  if (!items || items.length === 0) {
    doc.text("No data available", { italic: true });
  } else {
    items.forEach((item) => {
      doc.text(`• ${item}`);
    });
  }

  doc.moveDown();
};

const scoreBox = (doc, label, score, bgColor, textColor) => {
  const y = doc.y;

  doc
    .roundedRect(50, y, 500, 70, 10)
    .fill(bgColor);

  doc
    .fillColor(textColor)
    .font("Helvetica-Bold")
    .fontSize(14)
    .text(label, 70, y + 15);

  doc
    .fontSize(28)
    .text(`${score ?? "N/A"}/100`, 70, y + 30);

  doc.moveDown(4);
};

// ---------- Resume Report ----------

const generateResumeReport = async (req, res) => {
  try {
    const { resumeId } = req.params;

    if (!mongoose.Types.ObjectId.isValid(resumeId)) {
      return res.status(400).json({ message: "Invalid Resume ID" });
    }

    const report = await AnalysisReport.findOne({
      resumeId,
      userId: req.user,
    });

    if (!report) {
      return res.status(404).json({ message: "Report not found" });
    }

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=Resume_Report.pdf"
    );

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // HEADER
    doc.rect(0, 0, doc.page.width, 80).fill("#4F46E5");

    doc
      .fillColor("white")
      .font("Helvetica-Bold")
      .fontSize(22)
      .text("InsightCV", 50, 30);

    doc
      .fontSize(10)
      .text("Resume Analysis Report", 50, 55);

    doc.moveDown(4);
    doc.fillColor("black");

    // SCORE
    scoreBox(doc, "ATS SCORE", report.atsScore, "#EEF2FF", "#1E3A8A");

    // CONTENT
    divider(doc);

    sectionTitle(doc, "Overview");
    doc.fontSize(12).fillColor("#374151");
    doc.text(
      `Experience Level: ${report.experienceLevelDetected || "Unknown"}`
    );
    doc.moveDown();

    divider(doc);

    sectionTitle(doc, "Detected Skills");
    list(doc, report.detectedSkills);

    sectionTitle(doc, "Missing Keywords");
    list(doc, report.missingKeywords);

    divider(doc);

    sectionTitle(doc, "Strengths");
    list(doc, report.strengths);

    sectionTitle(doc, "Weaknesses");
    list(doc, report.weaknesses);

    sectionTitle(doc, "Suggestions");
    list(doc, report.suggestions);

    // FOOTER
    doc.moveDown(2);
    divider(doc);

    doc
      .fontSize(10)
      .fillColor("#6B7280")
      .text(
        `Generated by InsightCV • ${new Date().toLocaleDateString()}`,
        { align: "center" }
      );

    doc.end();
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error generating report" });
  }
};

// ---------- Job Match Report ----------

const generateJobMatchReport = async (req, res) => {
  try {
    const { resumeId } = req.params;

    if (!mongoose.Types.ObjectId.isValid(resumeId)) {
      return res.status(400).json({ message: "Invalid Resume ID" });
    }

    const report = await AnalysisReport.findOne({
      resumeId,
      userId: req.user,
    });

    if (!report || !report.jobMatchAnalysis) {
      return res.status(404).json({ message: "Job Match Report not found" });
    }

    const job = report.jobMatchAnalysis;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=Job_Match_Report.pdf"
    );

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    // HEADER
    doc.rect(0, 0, doc.page.width, 80).fill("#10B981");

    doc
      .fillColor("white")
      .font("Helvetica-Bold")
      .fontSize(22)
      .text("InsightCV", 50, 30);

    doc
      .fontSize(10)
      .text("Job Match Report", 50, 55);

    doc.moveDown(4);
    doc.fillColor("black");

    // SCORE
    scoreBox(doc, "MATCH SCORE", job.matchScore, "#ECFDF5", "#065F46");

    // CONTENT
    divider(doc);

    sectionTitle(doc, "Overview");
    doc.text(`Keyword Match: ${job.keywordMatchPercentage ?? "N/A"}%`);
    doc.moveDown();

    if (job.overallFeedback) {
      divider(doc);
      sectionTitle(doc, "Overall Feedback");
      doc.text(job.overallFeedback);
      doc.moveDown();
    }

    divider(doc);

    sectionTitle(doc, "Matching Skills");
    list(doc, job.matchingSkills);

    sectionTitle(doc, "Missing Skills");
    list(doc, job.missingSkillsForJob);

    sectionTitle(doc, "Improvement Suggestions");
    list(doc, job.improvementSuggestions);

    if (job.jobDescription) {
      divider(doc);
      sectionTitle(doc, "Job Description");

      const short =
        job.jobDescription.length > 400
          ? job.jobDescription.slice(0, 400) + "..."
          : job.jobDescription;

      doc.fontSize(10).text(short);
    }

    // FOOTER
    doc.moveDown(2);
    divider(doc);

    doc
      .fontSize(10)
      .fillColor("#6B7280")
      .text(
        `Generated by InsightCV • ${new Date().toLocaleDateString()}`,
        { align: "center" }
      );

    doc.end();
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error generating report" });
  }
};

module.exports = {
  generateResumeReport,
  generateJobMatchReport,
};